#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Deep Automated Essay Scoring for ELLs                                               #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.4                                                                              #
# Filename   : /logging.yml                                                                        #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/Deep-Automated-Essay-Scoring-for-ELLs              #
# ------------------------------------------------------------------------------------------------ #
# Created    : Monday September 5th 2022 10:50:51 pm                                               #
# Modified   : Wednesday September 7th 2022 05:10:27 am                                            #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #

---

version: 1
disable_existing_loggers: False
formatters:
    multiprocess:
        format: "%(levelname)s | %(asctime)s | %(module)s | %(process)d  | %(thread)d  | %(message)s"
    verbose:
        format: "%(levelname)s | %(asctime)s | %(module)s | %(message)s"
    standard:
        format: "%(levelname)s | %(asctime)s | %(message)s}"
    simple:
        format: "%(message)s"

handlers:
    console:
        level: INFO
        class: logging.StreamHandler
        formatter: simple
    logfile:
        level: INFO
        class: logging.handlers.TimedRotatingFileHandler
        formatter: verbose
        filename: logs/aes.log
        when: D
        backupCount: 3
loggers:
    root:
        handlers:
            - console
            - logfile
        propagate: False
        level: INFO
...